### ISSUE TITLE
lockProperties() interferes with 3rd party plugins

### ISSUE THREAD

**Issue by tpetry** [wire-elements/livewire-strict#1]
3rd party components e.g. Filament can't work when `lockProperties()` is activated because they (obvioulsy) don't use the package and have not unlocked their components yet. So it would be great if e.g. all components in `vendor` could be excluded. 

For components that extend vendored components it would be tricky too. So maybe an additional opt-in/opt-out for specific `App` namespaces would be great. But that would probably make Livewire less strict when the strict mode is configured bad? So any non-vendir should maybe just use `#[Unlocked]` for the whole class?

**Comment by PhiloNL** [comment]
Thanks @tpetry 😄 Working on a solution for this 🙌🏻

**Comment by DanjBethel** [comment]
Any traction on this? Currently having this same issue with Laravel Pulse

**Comment by PhiloNL** [comment]
@tpetry @DanjBethel added this:
https://github.com/wire-elements/livewire-strict/releases/tag/2.0.0

By default, it will only lock components inside the `App\Livewire\*` namespace. If you want you can override this:

```php
LivewireStrict::lockProperties(components: [MyComponent::class, 'SomeNamespaces/*']);
```
